// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl0y68X3LWjMYtRkMxlNF5JvqVfY3jDak',
    appId: '1:713404684682:web:250db4732e7863a7ad9073',
    messagingSenderId: '713404684682',
    projectId: 'jawara-f91b6',
    authDomain: 'jawara-f91b6.firebaseapp.com',
    storageBucket: 'jawara-f91b6.firebasestorage.app',
    measurementId: 'G-5F1NJFTQ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEM3OyYD8RoAEka9-O6YTpS-sty_VYZg',
    appId: '1:713404684682:android:53d972414385653dad9073',
    messagingSenderId: '713404684682',
    projectId: 'jawara-f91b6',
    storageBucket: 'jawara-f91b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdi5Ca-FAr-50HudOIZ3nNYzzZJEBZ5Jw',
    appId: '1:713404684682:ios:ba7b1be8358c5b13ad9073',
    messagingSenderId: '713404684682',
    projectId: 'jawara-f91b6',
    storageBucket: 'jawara-f91b6.firebasestorage.app',
    iosBundleId: 'com.example.jawara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdi5Ca-FAr-50HudOIZ3nNYzzZJEBZ5Jw',
    appId: '1:713404684682:ios:ba7b1be8358c5b13ad9073',
    messagingSenderId: '713404684682',
    projectId: 'jawara-f91b6',
    storageBucket: 'jawara-f91b6.firebasestorage.app',
    iosBundleId: 'com.example.jawara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl0y68X3LWjMYtRkMxlNF5JvqVfY3jDak',
    appId: '1:713404684682:web:6887df99d6c4d42ead9073',
    messagingSenderId: '713404684682',
    projectId: 'jawara-f91b6',
    authDomain: 'jawara-f91b6.firebaseapp.com',
    storageBucket: 'jawara-f91b6.firebasestorage.app',
    measurementId: 'G-NY57GK2NBT',
  );
}
