// model untuk pengeluaran
class KegiatanModel {
  int? id;
  String namaKegiatan, kategoriKegiatan, penanggungJawab, deskripsi,lokasi, dibuatOleh,dokumentasi;
  DateTime tanggalPelaksanaan;

  KegiatanModel({
    this.id,
    required this.namaKegiatan,
    required this.kategoriKegiatan,
    required this.penanggungJawab,
    required this.deskripsi,
    required this.tanggalPelaksanaan,
    required this.lokasi,
    required this.dibuatOleh,
    required this.dokumentasi,
  });

  // konversi dari map ke object
  factory KegiatanModel.fromMap(Map<String, dynamic> map) {
    return KegiatanModel(
      id: map['id'],
      namaKegiatan: map['nama_pengeluaran'],
      tanggalPelaksanaan: DateTime.parse(map['tanggal_pengeluaran']),
      kategoriKegiatan: map['kategori_pengeluaran'],
      penanggungJawab: map['penanggungJawab'],
      deskripsi: map['deskripsi'],
      lokasi: map['lokasi'],
      dibuatOleh: map['dibuatOleh'],
      dokumentasi: map['dokumentasi'],
    );
  }

  // konversi dari object ke map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'nama_pengeluaran': namaKegiatan,
      'kategori_pengeluaran': kategoriKegiatan,
      'penanggungJawab': penanggungJawab,
      'deskripsi': deskripsi,
      'tanggal_pengeluaran': tanggalPelaksanaan.toIso8601String(),
      'lokasi': lokasi,
      'dibuatOleh': dibuatOleh,
      'dokumentasi': dokumentasi,
    };
  }
}

List<KegiatanModel> dummyPengeluaran = [
  KegiatanModel(
    id: 1,
    namaKegiatan: 'Workshop Flutter',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'John Doe',
    deskripsi: 'Pelatihan pengembangan aplikasi menggunakan Flutter.',
    tanggalPelaksanaan: DateTime(2025, 10, 20),
    lokasi: 'Jakarta',
    dibuatOleh: 'Admin',
    dokumentasi: 'workshop_flutter.jpg',
  ),
  KegiatanModel(
    id: 2,
    namaKegiatan: 'Seminar AI',
    kategoriKegiatan: 'Seminar',
    penanggungJawab: 'Jane Smith',
    deskripsi: 'Seminar tentang perkembangan Artificial Intelligence.',
    tanggalPelaksanaan: DateTime(2025, 10, 22),
    lokasi: 'Bandung',
    dibuatOleh: 'Admin',
    dokumentasi: 'seminar_ai.jpg',
  ),
  KegiatanModel(
    id: 3,
    namaKegiatan: 'Hackathon 2025',
    kategoriKegiatan: 'Kompetisi',
    penanggungJawab: 'Alice Johnson',
    deskripsi: 'Kompetisi pengembangan aplikasi dalam waktu 24 jam.',
    tanggalPelaksanaan: DateTime(2025, 10, 25),
    lokasi: 'Surabaya',
    dibuatOleh: 'Admin',
    dokumentasi: 'hackathon_2025.jpg',
  ),
  KegiatanModel(
    id: 4,
    namaKegiatan: 'Pelatihan UI/UX',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Bob Brown',
    deskripsi: 'Pelatihan desain antarmuka pengguna dan pengalaman pengguna.',
    tanggalPelaksanaan: DateTime(2025, 10, 28),
    lokasi: 'Yogyakarta',
    dibuatOleh: 'Admin',
    dokumentasi: 'pelatihan_uiux.jpg',
  ),
  KegiatanModel(
    id: 5,
    namaKegiatan: 'Webinar Cloud Computing',
    kategoriKegiatan: 'Webinar',
    penanggungJawab: 'Charlie Green',
    deskripsi: 'Webinar tentang teknologi cloud computing.',
    tanggalPelaksanaan: DateTime(2025, 11, 1),
    lokasi: 'Online',
    dibuatOleh: 'Admin',
    dokumentasi: 'webinar_cloud.jpg',
  ),
  KegiatanModel(
    id: 6,
    namaKegiatan: 'Lomba Desain Poster',
    kategoriKegiatan: 'Kompetisi',
    penanggungJawab: 'Diana White',
    deskripsi: 'Kompetisi desain poster dengan tema lingkungan.',
    tanggalPelaksanaan: DateTime(2025, 11, 5),
    lokasi: 'Malang',
    dibuatOleh: 'Admin',
    dokumentasi: 'lomba_poster.jpg',
  ),
  KegiatanModel(
    id: 7,
    namaKegiatan: 'Pelatihan Data Science',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Eve Black',
    deskripsi: 'Pelatihan analisis data menggunakan Python.',
    tanggalPelaksanaan: DateTime(2025, 11, 10),
    lokasi: 'Semarang',
    dibuatOleh: 'Admin',
    dokumentasi: 'pelatihan_data.jpg',
  ),
  KegiatanModel(
    id: 8,
    namaKegiatan: 'Seminar Keamanan Siber',
    kategoriKegiatan: 'Seminar',
    penanggungJawab: 'Frank Blue',
    deskripsi: 'Seminar tentang pentingnya keamanan siber.',
    tanggalPelaksanaan: DateTime(2025, 11, 15),
    lokasi: 'Medan',
    dibuatOleh: 'Admin',
    dokumentasi: 'seminar_siber.jpg',
  ),
  KegiatanModel(
    id: 9,
    namaKegiatan: 'Workshop IoT',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Grace Yellow',
    deskripsi: 'Pelatihan pengembangan perangkat IoT.',
    tanggalPelaksanaan: DateTime(2025, 11, 20),
    lokasi: 'Makassar',
    dibuatOleh: 'Admin',
    dokumentasi: 'workshop_iot.jpg',
  ),
  KegiatanModel(
    id: 10,
    namaKegiatan: 'Hackathon Pemula',
    kategoriKegiatan: 'Kompetisi',
    penanggungJawab: 'Hank Red',
    deskripsi: 'Kompetisi pengembangan aplikasi untuk pemula.',
    tanggalPelaksanaan: DateTime(2025, 11, 25),
    lokasi: 'Bali',
    dibuatOleh: 'Admin',
    dokumentasi: 'hackathon_pemula.jpg',
  ),
  KegiatanModel(
    id: 11,
    namaKegiatan: 'Pelatihan Machine Learning',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Ivy Pink',
    deskripsi: 'Pelatihan dasar-dasar machine learning.',
    tanggalPelaksanaan: DateTime(2025, 12, 1),
    lokasi: 'Solo',
    dibuatOleh: 'Admin',
    dokumentasi: 'pelatihan_ml.jpg',
  ),
  KegiatanModel(
    id: 12,
    namaKegiatan: 'Seminar Blockchain',
    kategoriKegiatan: 'Seminar',
    penanggungJawab: 'Jack Purple',
    deskripsi: 'Seminar tentang teknologi blockchain.',
    tanggalPelaksanaan: DateTime(2025, 12, 5),
    lokasi: 'Palembang',
    dibuatOleh: 'Admin',
    dokumentasi: 'seminar_blockchain.jpg',
  ),
  KegiatanModel(
    id: 13,
    namaKegiatan: 'Lomba Fotografi',
    kategoriKegiatan: 'Kompetisi',
    penanggungJawab: 'Karen Orange',
    deskripsi: 'Kompetisi fotografi dengan tema budaya.',
    tanggalPelaksanaan: DateTime(2025, 12, 10),
    lokasi: 'Padang',
    dibuatOleh: 'Admin',
    dokumentasi: 'lomba_foto.jpg',
  ),
  KegiatanModel(
    id: 14,
    namaKegiatan: 'Webinar DevOps',
    kategoriKegiatan: 'Webinar',
    penanggungJawab: 'Leo Gray',
    deskripsi: 'Webinar tentang pengenalan DevOps.',
    tanggalPelaksanaan: DateTime(2025, 12, 15),
    lokasi: 'Online',
    dibuatOleh: 'Admin',
    dokumentasi: 'webinar_devops.jpg',
  ),
  KegiatanModel(
    id: 15,
    namaKegiatan: 'Pelatihan Cloud Security',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Mona Cyan',
    deskripsi: 'Pelatihan keamanan cloud.',
    tanggalPelaksanaan: DateTime(2025, 12, 20),
    lokasi: 'Balikpapan',
    dibuatOleh: 'Admin',
    dokumentasi: 'pelatihan_cloud.jpg',
  ),
  KegiatanModel(
    id: 16,
    namaKegiatan: 'Seminar Big Data',
    kategoriKegiatan: 'Seminar',
    penanggungJawab: 'Nina Lime',
    deskripsi: 'Seminar tentang pengolahan big data.',
    tanggalPelaksanaan: DateTime(2025, 12, 25),
    lokasi: 'Pontianak',
    dibuatOleh: 'Admin',
    dokumentasi: 'seminar_bigdata.jpg',
  ),
  KegiatanModel(
    id: 17,
    namaKegiatan: 'Workshop AR/VR',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Oscar Indigo',
    deskripsi: 'Pelatihan pengembangan aplikasi AR/VR.',
    tanggalPelaksanaan: DateTime(2026, 1, 5),
    lokasi: 'Manado',
    dibuatOleh: 'Admin',
    dokumentasi: 'workshop_arvr.jpg',
  ),
  KegiatanModel(
    id: 18,
    namaKegiatan: 'Lomba Animasi',
    kategoriKegiatan: 'Kompetisi',
    penanggungJawab: 'Paul Violet',
    deskripsi: 'Kompetisi pembuatan animasi pendek.',
    tanggalPelaksanaan: DateTime(2026, 1, 10),
    lokasi: 'Jayapura',
    dibuatOleh: 'Admin',
    dokumentasi: 'lomba_animasi.jpg',
  ),
  KegiatanModel(
    id: 19,
    namaKegiatan: 'Webinar Kubernetes',
    kategoriKegiatan: 'Webinar',
    penanggungJawab: 'Quinn Magenta',
    deskripsi: 'Webinar tentang pengenalan Kubernetes.',
    tanggalPelaksanaan: DateTime(2026, 1, 15),
    lokasi: 'Online',
    dibuatOleh: 'Admin',
    dokumentasi: 'webinar_kubernetes.jpg',
  ),
  KegiatanModel(
    id: 20,
    namaKegiatan: 'Pelatihan Cybersecurity',
    kategoriKegiatan: 'Pelatihan',
    penanggungJawab: 'Rita Gold',
    deskripsi: 'Pelatihan dasar-dasar keamanan siber.',
    tanggalPelaksanaan: DateTime(2026, 1, 20),
    lokasi: 'Batam',
    dibuatOleh: 'Admin',
    dokumentasi: 'pelatihan_cyber.jpg',
  ),
];
